### ISSUE TITLE
Visualization - US, Canada, and Mexico's Performance on the EPI 

### ISSUE THREAD

**Issue by Gustavomurillov** [Gustavomurillov/assignment04#8]
Objective: Compare the performance of the US, Canada, and Mexico in the Environmental Performance Index 2022 (https://epi.yale.edu/epi-results/2022/component/epi)

In addition to comparing the overall score, we can compare their score in each of the three policy objectives measured by the INDEX to find out if there are any important differences across the sub-scores.
Use geom_bar and geom_text

**Comment by sc2105** [comment]
you can also facet_wrap to show each country's score separately/in comparison to each other
